# %APPDATA%\alacritty\alacritty.toml

# select wsl distro and cd $HOME
shell =  { program = "C:\\Windows\\System32\\wsl.exe", args = ["-d Arch", "--cd ~"] }

[window]
position = { x = 300, y = 120 }
dimensions = { columns = 110, lines = 35 }
opacity = 0.8
decorations =  "None"
blur = true

[font] # can be downloaded at https://www.nerdfonts.com/font-downloads
size = 15
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font" }
italic = { family = "FiraCode Nerd Font" }
bold_italic = { family = "FiraCode Nerd Font" }

[mouse]
hide_when_typing = true

# Colors (Everforest Dark)

# Default colors
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
