#!/bin/zsh

# export JAVA_HOME=/usr/lib/jvm/default
# export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH

# export PATH=$JAVA_HOME/bin:/usr/local/cuda/bin:$HOME/.bin:$PATH
export PATH=$HOME/.scripts:$PATH
export MAKEFLAGS="-j $(grep processor /proc/cpuinfo | wc -l)"

# common options
export LANG=en_US.UTF-8
export TIME_STYLE='+%y/%m/%d %H:%M:%S'
export HIST_STAMPS="yyyy-mm-dd"

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
# setproxy
export all_proxy="192.168.0.105:7890"
export http_proxy="192.168.0.105:7890"
export https_proxy="192.168.0.105:7890"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.scripts/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
